apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: armaan24katyal/go-oauth2
          name: server1
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/health
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      hostname: server
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}
